language: node_js
sudo: required
node_js:
  - "8"
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm i -g @zodern/mtest

env:
  global:
    - TEST_COMMAND=meteor
    - AUTOUPDATE_VERSION='abc'
  matrix:
    - METEOR_RELEASE=1.4.4.5
    - METEOR_RELEASE=1.5.4.1
    - METEOR_RELEASE=1.6.1
    - METEOR_RELEASE=1.7.0.5
    - METEOR_RELASE=1.8.0.2
    - METEOR_RELEASE=1.8.1-beta.17
script: mtest --package ./ --once --release $METEOR_RELEASE
