language: node_js
sudo: required
node_js:
  - "8"
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm i -g @zodern/mtest

env:
  global:
    - TEST_COMMAND=meteor
    - AUTOUPDATE_VERSION='abc'
  matrix:
    - METEOR_RELEASE=1.4.4.5
    - METEOR_RELEASE=1.5.4.1
    - METEOR_RELEASE=1.6.0.1
    - METEOR_RELEASE=1.7.0.5
    - METEOR_RELEASE=1.8.1
    - METEOR_RELEASE=1.8.3
    - METEOR_RELEASE=1.9.1
    - METEOR_RELEASE=1.10.2
    - METEOR_RELEASE=1.11

# Retry tests since some of them are flaky
script: mtest --package ./ --once --release $METEOR_RELEASE || mtest --package ./ --once --release $METEOR_RELEASE
